package com.order_service.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * OrderItem entity representing a single item within an order.
 * 
 * <p>This entity stores item information including:
 * <ul>
 *   <li>Product reference (idProduct, nameProduct)</li>
 *   <li>Quantity ordered</li>
 *   <li>Pricing information (unitPrice, totalPrice)</li>
 * </ul>
 * 
 * @see Order
 */
@Entity
@Table(name = "order_items")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderItem {

    /**
     * Unique identifier for the order item.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Reference to the product ID in the product catalog.
     */
    @Column(name = "id_product")
    private Long idProduct;

    /**
     * Name of the product at the time of order.
     * Stored to preserve order history even if product name changes.
     */
    @Column(name = "name_product", length = 255)
    private String nameProduct;

    /**
     * Quantity of this product ordered.
     */
    @Column(name = "quantity")
    private Integer quantity;

    /**
     * Unit price of the product at the time of order.
     * Stored to preserve order history even if product price changes.
     */
    @Column(name = "unit_price")
    private Double unitPrice;

    /**
     * Total price for this line item (unitPrice * quantity).
     * Rounded to two decimal places.
     */
    @Column(name = "total_price")
    private Double totalPrice;

}