package com.order_service.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Order entity representing a customer order in the system.
 * 
 * <p>This entity stores order information including:
 * <ul>
 *   <li>Customer information (name, lastName, email, address, phone)</li>
 *   <li>Order items and total amount</li>
 *   <li>Order status and date</li>
 * </ul>
 * 
 * <p>The order date is automatically set when the order is persisted.
 * 
 * @see OrderItem
 * @see StatusOrder
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    /**
     * Unique identifier for the order.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "order_id")
    private Long orderId;

    /**
     * Customer's first name.
     */
    @Column(name = "name", length = 100)
    private String name;

    /**
     * Customer's last name.
     */
    @Column(name = "last_name", length = 100)
    private String lastName;

    /**
     * Customer's email address.
     * Used for order notifications and lookup.
     */
    @Column(name = "email", length = 255)
    private String email;

    /**
     * Customer's role in the system.
     */
    @Column(name = "role", length = 20)
    private String role;

    /**
     * Shipping address for the order.
     */
    @Column(name = "address", length = 255)
    private String address;

    /**
     * Customer's contact phone number.
     */
    @Column(name = "phone", length = 20)
    private String phone;

    /**
     * List of items included in this order.
     * Cascade all operations and remove orphans.
     */
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "order_id")
    private List<OrderItem> items;

    /**
     * Total amount for the order.
     * Rounded to two decimal places.
     */
    @Column(name = "total_amount")
    private Double totalAmount;

    /**
     * Current status of the order.
     * 
     * @see StatusOrder
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "order_status")
    private StatusOrder orderStatus;

    /**
     * Date and time when the order was created.
     * Automatically set when the order is persisted.
     */
    @Column(name = "order_date")
    private LocalDateTime orderDate;

    /**
     * Lifecycle callback that sets the order date before persisting.
     */
    @PrePersist
    protected void onCreate() {
        this.orderDate = LocalDateTime.now();
    }

    /**
     * Enum representing the possible statuses of an order.
     * 
     * <ul>
     *   <li>PENDING - Order has been created but not yet processed</li>
     *   <li>PROCESSING - Order is being prepared/processed</li>
     *   <li>COMPLETED - Order has been fulfilled</li>
     * </ul>
     */
    public enum StatusOrder {
        PENDING,
        PROCESSING,
        COMPLETED
    }

}