package com.auth_service_api.entity;

import com.auth_service_api.enums.UserRole;
import jakarta.persistence.*;
import lombok.*;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * User entity representing a registered user in the system.
 * 
 * <p>This entity stores user information including:
 * <ul>
 *   <li>Personal information (name, last name, email)</li>
 *   <li>Authentication credentials (password - hashed)</li>
 *   <li>Authorization information (role)</li>
 *   <li>Optional contact information (address, phone)</li>
 * </ul>
 * 
 * <p>The password field is excluded from JSON serialization for security purposes.
 * 
 * @see UserRole
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Unique identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * User's first name.
     * Required field, cannot be null.
     */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /**
     * User's last name.
     * Required field, cannot be null.
     */
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    /**
     * User's email address.
     * Required field, must be unique across all users.
     * Used for authentication and communication.
     */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    /**
     * User's hashed password.
     * Required field, cannot be null.
     * Excluded from JSON serialization for security (WRITE_ONLY).
     * Should be hashed using BCrypt before storage.
     */
    @Column(name = "password", nullable = false)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    /**
     * User's role in the system.
     * Required field, determines user permissions.
     * Can be either ADMIN or CLIENT.
     * 
     * @see UserRole
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    private UserRole role;

    /**
     * User's address.
     * Optional field.
     */
    @Column(name = "address", length = 255)
    private String address;

    /**
     * User's phone number.
     * Optional field.
     */
    @Column(name = "phone", length = 20)
    private String phone;
}